<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Measure model performance through fit, comparisons, and reliability.">
<title>Evaluate model performance – r-dcm</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/img/favicon-96x96.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-b3aaa6997641482631754dbbac2f39fc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0f96150053b5d64986f732095ddb08ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script data-goatcounter="https://r-dcm.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">r-dcm</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link active" href="../../start/index.html" aria-current="page"> 
<span class="menu-text">Get Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../team/index.html"> 
<span class="menu-text">Our Team</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/r-dcm"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../start/evaluate/index.html">Evaluate model performance</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GET STARTED</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/specify/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Specify a diagnostic model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/evaluate/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Evaluate model performance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/hierarchies/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Define attribute relationships</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/case-study/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A diagnostic assessment case study</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#diagnosing-teachers-multiplicative-reasoning-dtmr-data" id="toc-diagnosing-teachers-multiplicative-reasoning-dtmr-data" class="nav-link" data-scroll-target="#diagnosing-teachers-multiplicative-reasoning-dtmr-data">Diagnosing Teachers’ Multiplicative Reasoning (DTMR) data</a></li>
  <li>
<a href="#absolute-model-fit" id="toc-absolute-model-fit" class="nav-link" data-scroll-target="#absolute-model-fit">Absolute model fit</a>
  <ul class="collapse">
<li><a href="#m2-statistic" id="toc-m2-statistic" class="nav-link" data-scroll-target="#m2-statistic">M<sub>2</sub> statistic</a></li>
  <li><a href="#posterior-predictive-model-checks" id="toc-posterior-predictive-model-checks" class="nav-link" data-scroll-target="#posterior-predictive-model-checks">Posterior predictive model checks</a></li>
  </ul>
</li>
  <li><a href="#relative-model-fit" id="toc-relative-model-fit" class="nav-link" data-scroll-target="#relative-model-fit">Relative model fit</a></li>
  <li>
<a href="#classification-reliability" id="toc-classification-reliability" class="nav-link" data-scroll-target="#classification-reliability">Classification reliability</a>
  <ul class="collapse">
<li><a href="#pattern-reliability" id="toc-pattern-reliability" class="nav-link" data-scroll-target="#pattern-reliability">Pattern reliability</a></li>
  <li><a href="#map-reliability" id="toc-map-reliability" class="nav-link" data-scroll-target="#map-reliability">MAP reliability</a></li>
  <li><a href="#eap-reliability" id="toc-eap-reliability" class="nav-link" data-scroll-target="#eap-reliability">EAP reliability</a></li>
  </ul>
</li>
  <li><a href="#wrapping-up" id="toc-wrapping-up" class="nav-link" data-scroll-target="#wrapping-up">Wrapping up</a></li>
  
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Evaluate model performance</h1>
</div>

<div>
  <div class="description">
    <p>Measure model performance through fit, comparisons, and reliability.</p>
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduction" class="level2"><h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Once you’ve estimated a DCM, the natural next question is: <em>does this model actually work?</em> Before reporting results or making decisions based on proficiency classifications, we want evidence that the model is doing a good job of representing the data. In this article, we’ll walk through four complementary approaches to evaluating a DCM:</p>
<ul>
<li>Absolute fit: Does the model fit the observed data?</li>
<li>Relative fit: When comparing competing models, which one fits better?</li>
<li>Classification reliability: How consistent and accurate are the proficiency classifications?</li>
<li>Misfit diagnostics: If something seems off, where is the problem?</li>
</ul>
<p>To use code in this article, you will need to install the following packages: <a href="https://dcmdata.r-dcm.org">dcmdata</a>, <a href="https://measr.r-dcm.org">measr</a>, and <a href="https://mc-stan.org/rstan/">rstan</a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://measr.r-dcm.org">measr</a></span><span class="op">)</span> <span class="co"># for model evaluation</span></span>
<span></span>
<span><span class="co"># Helper packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dcmdata.r-dcm.org">dcmdata</a></span><span class="op">)</span> <span class="co"># for example data set</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstan/">rstan</a></span><span class="op">)</span> <span class="co"># for estimation backend</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="diagnosing-teachers-multiplicative-reasoning-dtmr-data" class="level2"><h2 class="anchored" data-anchor-id="diagnosing-teachers-multiplicative-reasoning-dtmr-data">Diagnosing Teachers’ Multiplicative Reasoning (DTMR) data</h2>
<p>We’ll use data from the DTMR project to demonstrate each of these evaluation tools. The DTMR assessment measures four attributes related to multiplicative reasoning in mathematics teachers. In total, the DTMR data contains responses to 27 items from 990 respondents.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dtmr_data</span></span>
<span><span class="co">#&gt; # A tibble: 990 × 28</span></span>
<span><span class="co">#&gt;    id      `1`   `2`   `3`   `4`   `5`   `6`   `7`  `8a`  `8b`  `8c`  `8d`   `9`</span></span>
<span><span class="co">#&gt;    &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt;  1 0008…     1     1     0     1     0     0     1     1     0     1     1     0</span></span>
<span><span class="co">#&gt;  2 0009…     0     1     0     0     0     0     0     1     1     1     0     1</span></span>
<span><span class="co">#&gt;  3 0024…     0     1     0     0     0     0     1     1     1     1     0     0</span></span>
<span><span class="co">#&gt;  4 0031…     0     1     0     0     1     0     1     1     1     0     0     0</span></span>
<span><span class="co">#&gt;  5 0061…     0     1     1     0     0     0     0     0     0     1     0     0</span></span>
<span><span class="co">#&gt;  6 0087…     0     1     1     1     0     0     0     1     1     1     1     0</span></span>
<span><span class="co">#&gt;  7 0092…     0     1     1     1     1     0     0     1     1     1     0     0</span></span>
<span><span class="co">#&gt;  8 0097…     0     0     0     1     0     0     0     1     0     1     0     0</span></span>
<span><span class="co">#&gt;  9 0111…     0     1     1     0     0     0     0     1     0     1     1     0</span></span>
<span><span class="co">#&gt; 10 0121…     0     1     0     0     0     0     0     1     1     1     1     0</span></span>
<span><span class="co">#&gt; # ℹ 980 more rows</span></span>
<span><span class="co">#&gt; # ℹ 15 more variables: `10a` &lt;int&gt;, `10b` &lt;int&gt;, `10c` &lt;int&gt;, `11` &lt;int&gt;,</span></span>
<span><span class="co">#&gt; #   `12` &lt;int&gt;, `13` &lt;int&gt;, `14` &lt;int&gt;, `15a` &lt;int&gt;, `15b` &lt;int&gt;, `15c` &lt;int&gt;,</span></span>
<span><span class="co">#&gt; #   `16` &lt;int&gt;, `17` &lt;int&gt;, `18` &lt;int&gt;, `21` &lt;int&gt;, `22` &lt;int&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Alongside the response data, we also have a Q-matrix that maps items to the 4 attributes measured by the assessment. These attributes represent aspects of multiplicative reasoning including and understanding of referent units, partitioning and iterating, appropriateness, and multiplicative comparison. For more information on the data set, see <code><a href="https://dcmdata.r-dcm.org/reference/dtmr.html">?dtmr</a></code> and <span class="citation" data-cites="dtmr">Bradshaw et al. (<a href="#ref-dtmr" role="doc-biblioref">2014</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dtmr_qmatrix</span></span>
<span><span class="co">#&gt; # A tibble: 27 × 5</span></span>
<span><span class="co">#&gt;    item  referent_units partitioning_iterating appropriateness</span></span>
<span><span class="co">#&gt;    &lt;chr&gt;          &lt;dbl&gt;                  &lt;dbl&gt;           &lt;dbl&gt;</span></span>
<span><span class="co">#&gt;  1 1                  1                      0               0</span></span>
<span><span class="co">#&gt;  2 2                  0                      0               1</span></span>
<span><span class="co">#&gt;  3 3                  0                      1               0</span></span>
<span><span class="co">#&gt;  4 4                  1                      0               0</span></span>
<span><span class="co">#&gt;  5 5                  1                      0               0</span></span>
<span><span class="co">#&gt;  6 6                  0                      1               0</span></span>
<span><span class="co">#&gt;  7 7                  1                      0               0</span></span>
<span><span class="co">#&gt;  8 8a                 0                      0               1</span></span>
<span><span class="co">#&gt;  9 8b                 0                      0               1</span></span>
<span><span class="co">#&gt; 10 8c                 0                      0               1</span></span>
<span><span class="co">#&gt; # ℹ 17 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: multiplicative_comparison &lt;dbl&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>One particularly useful feature of the DTMR data for learning purposes is that it was simulated from known parameters. The actual data set is not publicly available. However, dcmdata provides an artificial data set with the same number of items and respondents, using the parameter estimates reported by <span class="citation" data-cites="dtmr">Bradshaw et al. (<a href="#ref-dtmr" role="doc-biblioref">2014</a>)</span> and <span class="citation" data-cites="dtmr-strc">Izsák et al. (<a href="#ref-dtmr-strc" role="doc-biblioref">2019</a>)</span>. This means that the data set we are using will match the characterisitics of the real data, but we know what the true model parameters should be. For example, because this data was simulated from a loglinear cognitive diagnostic model <span class="citation" data-cites="lcdm">(LCDM; <a href="#ref-lcdm" role="doc-biblioref">Henson et al., 2009</a>)</span>, we know that we should see good model performance when estimating an LCDM to this data. Conversely, we should see poor performance if we estimate a more restrictive model, such as the deterministic input, noisy “and” gate model <span class="citation" data-cites="dina">(DINA; <a href="#ref-dina" role="doc-biblioref"><span class="nocase">de la Torre &amp; Douglas</span>, 2004</a>)</span>. And that’s exactly what makes this dataset a great learning example. We’ll see what both good and bad fit look like and learn how to recognize it.</p>
<p>Some of the evaluation tools we’ll use require the full Bayesian posterior distribution, which means we need to estimate the model using MCMC. Let’s specify and estimate two models now. First, we’ll estimate and LCDM that we know should show good fit and performance.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_spec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/dcm_specify.html">dcm_specify</a></span><span class="op">(</span></span>
<span>  qmatrix <span class="op">=</span> <span class="va">dtmr_qmatrix</span>,</span>
<span>  identifier <span class="op">=</span> <span class="st">"item"</span>,</span>
<span>  measurement_model <span class="op">=</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/measurement-model.html">lcdm</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  structural_model <span class="op">=</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/structural-model.html">unconstrained</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dtmr_lcdm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://measr.r-dcm.org/reference/dcm_estimate.html">dcm_estimate</a></span><span class="op">(</span></span>
<span>  <span class="va">lcdm_spec</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dtmr_data</span>,</span>
<span>  identifier <span class="op">=</span> <span class="st">"id"</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"mcmc"</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"rstan"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter <span class="op">=</span> <span class="fl">1500</span>,</span>
<span>  warmup <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  file <span class="op">=</span> <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"start"</span>, <span class="st">"fits"</span>, <span class="st">"dtmr-lcdm-mcmc-rstn"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Next, we’ll estimate a DINA model. The DINA model puts constraints on the LCDM, so this model should show worse performance than our LCDM.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dina_spec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/dcm_specify.html">dcm_specify</a></span><span class="op">(</span></span>
<span>  qmatrix <span class="op">=</span> <span class="va">dtmr_qmatrix</span>,</span>
<span>  identifier <span class="op">=</span> <span class="st">"item"</span>,</span>
<span>  measurement_model <span class="op">=</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/measurement-model.html">dina</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  structural_model <span class="op">=</span> <span class="fu"><a href="https://dcmstan.r-dcm.org/reference/structural-model.html">unconstrained</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dtmr_dina</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://measr.r-dcm.org/reference/dcm_estimate.html">dcm_estimate</a></span><span class="op">(</span></span>
<span>  <span class="va">dina_spec</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dtmr_data</span>,</span>
<span>  identifier <span class="op">=</span> <span class="st">"id"</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"mcmc"</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"rstan"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter <span class="op">=</span> <span class="fl">2500</span>,</span>
<span>  warmup <span class="op">=</span> <span class="fl">2000</span>,</span>
<span>  control <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>adapt_delta <span class="op">=</span> <span class="fl">.99</span><span class="op">)</span>,</span>
<span>  file <span class="op">=</span> <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"start"</span>, <span class="st">"fits"</span>, <span class="st">"dtmr-dina-mcmc-rstn"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="absolute-model-fit" class="level2"><h2 class="anchored" data-anchor-id="absolute-model-fit">Absolute model fit</h2>
<p>Absolute fit asks a direct question: does the model fit the data? We have two tools for answering it with measr: the M<sub>2</sub> statistic, which works with any estimation method, and posterior predictive model checks (PPMCs), which require a full posterior from either MCMC estimation or a variational inference algorithm.</p>
<section id="m2-statistic" class="level3"><h3 class="anchored" data-anchor-id="m2-statistic">M<sub>2</sub> statistic</h3>
<p>The M<sub>2</sub> statistic is a limited-information goodness-of-fit measure originally developed by Maydeu-Olivares &amp; Joe <span class="citation" data-cites="m2-2005 m2-2006">(<a href="#ref-m2-2005" role="doc-biblioref">2005</a>, <a href="#ref-m2-2006" role="doc-biblioref">2006</a>)</span> and adapted for DCMs by <span class="citation" data-cites="liu2016">Liu et al. (<a href="#ref-liu2016" role="doc-biblioref">2016</a>)</span>. “Limited-information” means the statistic summarizes fit using item-pair statistics rather than the full multivariate response pattern, making it practical for assessments with many items.</p>
<p>The null hypothesis is that the model fits the data. A large M<sub>2</sub> (relative to the degrees of freedom, <code>df</code>) with a small <em>p</em>-value suggests the model does not adequately reproduce the observed data patterns. We can calculate the M<sub>2</sub> for any measr model with <code><a href="https://rdrr.io/pkg/dcm2/man/fit_m2.html">fit_m2()</a></code>. In addition to the M<sub>2</sub> statistic and its <em>p</em>-value, the function also returns the root mean square error of approximation (RMSEA) with a 90% confidence interval and the standardized root mean square residual (SRMSR) as supplementary fit indices.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/dcm2/man/fit_m2.html">fit_m2</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 8</span></span>
<span><span class="co">#&gt;      m2    df  pval rmsea ci_lower ci_upper `90% CI`     srmsr</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  266.   293 0.869     0        0   0.0068 [0, 0.0068] 0.0273</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Since the DTMR data was generated from an LCDM, we expect good fit here. A non-significant <em>p</em>-value means we cannot reject the null hypothesis that the model fits, and small RMSEA and SRMSR values indicate the model closely reproduces the observed item-pair statistics.</p>
<p>Contrast that with the fit results for the DINA model. The M<sub>2</sub> is quite large with a very small <em>p</em>-value, and both the RMSEA and SRMSR are more elevated. This is expected in this example, because we know that the DINA model has more constraints than the model that was used to generate this data set.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/dcm2/man/fit_m2.html">fit_m2</a></span><span class="op">(</span><span class="va">dtmr_dina</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 8</span></span>
<span><span class="co">#&gt;      m2    df        pval  rmsea ci_lower ci_upper `90% CI`          srmsr</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;int&gt;       &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  452.   309 0.000000203 0.0216   0.0172   0.0258 [0.0172, 0.0258] 0.0719</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="posterior-predictive-model-checks" class="level3"><h3 class="anchored" data-anchor-id="posterior-predictive-model-checks">Posterior predictive model checks</h3>
<p>Posterior predictive model checks (PPMCs) are a Bayesian approach to evaluating model fit <span class="citation" data-cites="park2015">(<a href="#ref-park2015" role="doc-biblioref">Park et al., 2015</a>)</span>. The idea is to simulate many replicated datasets from the estimated model posterior, then ask: does our observed data look like data the model would generate? If the model is well-specified, the observed data should be indistinguishable from the replicated data.</p>
<p><code><a href="https://measr.r-dcm.org/reference/fit_ppmc.html">fit_ppmc()</a></code> performs a PPMC based on the raw score distribution. It simulates replicated datasets from the posterior, calculates the distribution of raw scores for each, and compares this distribution to our observed data. Because PPMCs require draws from the full posterior distribution, they only work with model estimated by a method that produces a posterior (i.e., MCMC, variational inference).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_ppmc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://measr.r-dcm.org/reference/fit_ppmc.html">fit_ppmc</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span>, model_fit <span class="op">=</span> <span class="st">"raw_score"</span><span class="op">)</span></span>
<span><span class="va">lcdm_ppmc</span></span>
<span><span class="co">#&gt; $ppmc_raw_score</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 5</span></span>
<span><span class="co">#&gt;   obs_chisq ppmc_mean `2.5%` `97.5%`   ppp</span></span>
<span><span class="co">#&gt;       &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1      35.6      30.0   13.1    56.8 0.201</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The key output is the posterior predictive <em>p</em>-value (<em>ppp</em>), which is the proportion of replicated datasets that produced a larger fit statistic than our observed data. For a well-fitting model, the observed data should fall in the middle of the replicated distribution, giving a <em>ppp</em> near 0.5. Values near 0 indicate that the observed data produces a fit statistic with a much larger value than expected by replicated datasets; values near 1 would indicate the opposite. In this case, our <em>ppp</em> values is 0.201, indicating that 20.1% of replicated data sets had a larger fit statistic than our observed data.</p>
<p>Let’s visualize the PPMC to see how the observed raw score distribution compares to the replicated data.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Plot code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mjskay.github.io/ggdist/">ggdist</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">obs_scores</span> <span class="op">&lt;-</span> <span class="va">dtmr_data</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="op">-</span><span class="st">"id"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>raw_score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">value</span><span class="op">)</span>, .by <span class="op">=</span> <span class="va">id</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">raw_score</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/complete.html">complete</a></span><span class="op">(</span>raw_score <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">dtmr_data</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>, fill <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">0L</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://measr.r-dcm.org/reference/fit_ppmc.html">fit_ppmc</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span>, model_fit <span class="op">=</span> <span class="st">"raw_score"</span>, return_draws <span class="op">=</span> <span class="fl">2000</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"ppmc_raw_score"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">rawscore_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/unnest.html">unnest</a></span><span class="op">(</span><span class="va">rawscore_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/unnest.html">unnest</a></span><span class="op">(</span><span class="va">raw_scores</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_interval.html">stat_interval</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">raw_score</span>, y <span class="op">=</span> <span class="va">n</span>, color_ramp <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes_eval.html">after_stat</a></span><span class="op">(</span><span class="va">level</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    point_interval <span class="op">=</span> <span class="st">"mean_qi"</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>    linewidth <span class="op">=</span> <span class="fl">5</span>,</span>
<span>    show.legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>color <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="va">obs_scores</span>,</span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">raw_score</span>, y <span class="op">=</span> <span class="va">n</span><span class="op">)</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="va">obs_scores</span>,</span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">raw_score</span>, y <span class="op">=</span> <span class="va">n</span>, fill <span class="op">=</span> <span class="st">"Observed Data"</span><span class="op">)</span>,</span>
<span>    shape <span class="op">=</span> <span class="fl">21</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">2</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/scale_colour_ramp.html">scale_color_ramp_discrete</a></span><span class="op">(</span></span>
<span>    from <span class="op">=</span> <span class="st">"white"</span>,</span>
<span>    range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.2</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>    breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">0.8</span>, <span class="fl">0.95</span><span class="op">)</span>,</span>
<span>    labels <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">.x</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span>, <span class="st">"%"</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">msr_colors</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">27</span>, <span class="fl">3</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_comma</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Raw score"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Respondents"</span>,</span>
<span>    color_ramp <span class="op">=</span> <span class="st">"Credible Interval"</span>,</span>
<span>    fill <span class="op">=</span> <span class="cn">NULL</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html">guide_legend</a></span><span class="op">(</span>override.aes <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-rawscore-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Line plot showing the observed number of respondents at each raw score point, superimposed over an interval showing the expected number of respondents at each score point from model-replicated data. The observed line runs through the middle of the credible interval bands, indicating good model fit.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rawscore-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-rawscore-dist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" alt="Line plot showing the observed number of respondents at each raw score point, superimposed over an interval showing the expected number of respondents at each score point from model-replicated data. The observed line runs through the middle of the credible interval bands, indicating good model fit.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rawscore-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Posterior predictive model check of the raw score distribution.
</figcaption></figure>
</div>
</div>
</div>
<p>The blue bars show the 50%, 80%, and 95% credible intervals for the expected number of respondents at each score point, based on the model (i.e., the distribution across the replicated data sets). The red line and points show the counts from our observed data set. When the model fits well, the red line threads through the middle of the blue intervals rather than wandering outside them.</p>
<p>We can also examine the distribution of χ<sup>2</sup>-like statistics calculated from the replicated datasets <span class="citation" data-cites="thompson-bayes">(<a href="#ref-thompson-bayes" role="doc-biblioref">Thompson, 2019</a>)</span>. For each replicated dataset, we compute how much it differs from the expected raw score distribution. This creates a distribution of plausible χ<sup>2</sup> values under the model. The χ<sup>2</sup> is our fit statistic in this PPMC, and the <em>ppp</em> value is the proportion of replicated χ<sup>2</sup> values that exceed the observed value (as indicated by the red line). In this example, we see that the observed value is toward the middle, which is exactly what we would expect from a well-fitting model.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Plot code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://measr.r-dcm.org/reference/fit_ppmc.html">fit_ppmc</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span>, model_fit <span class="op">=</span> <span class="st">"raw_score"</span>, return_draws <span class="op">=</span> <span class="fl">2000</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"ppmc_raw_score"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">chisq_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/unnest.html">unnest</a></span><span class="op">(</span><span class="va">chisq_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">chisq_samples</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_dots.html">stat_dots</a></span><span class="op">(</span></span>
<span>    quantiles <span class="op">=</span> <span class="fl">500</span>,</span>
<span>    layout <span class="op">=</span> <span class="st">"hex"</span>,</span>
<span>    stackratio <span class="op">=</span> <span class="fl">0.9</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>    fill <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>    na.rm <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span></span>
<span>    xintercept <span class="op">=</span> <span class="va">dtmr_lcdm</span><span class="op">@</span><span class="va">fit</span><span class="op">$</span><span class="va">ppmc_raw_score</span><span class="op">$</span><span class="va">obs_chisq</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,</span>
<span>    linewidth <span class="op">=</span> <span class="fl">1</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="cn">NULL</span>, x <span class="op">=</span> <span class="st">"&amp;chi;^2^&lt;sub&gt;rep&lt;/sub&gt;"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>, axis.ticks.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-chisq-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Dot plot showing the distribution of chi-square statistics from replicated datasets. A vertical line marks the observed chi-square statistic, which falls near the center of the distribution, indicating good model fit.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-chisq-dist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" alt="Dot plot showing the distribution of chi-square statistics from replicated datasets. A vertical line marks the observed chi-square statistic, which falls near the center of the distribution, indicating good model fit.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Posterior predictive χ<sup>2</sup> distribution for the LCDM.
</figcaption></figure>
</div>
</div>
</div>
<p>Compare this to the same χ<sup>2</sup> plot for the DINA model. For this model, the observed value is further out in the tail of the distribution of expected values. Accordingly, our <em>ppp</em> value is only 0.052.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Plot code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://measr.r-dcm.org/reference/fit_ppmc.html">fit_ppmc</a></span><span class="op">(</span><span class="va">dtmr_dina</span>, model_fit <span class="op">=</span> <span class="st">"raw_score"</span>, return_draws <span class="op">=</span> <span class="fl">2000</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"ppmc_raw_score"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">chisq_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/unnest.html">unnest</a></span><span class="op">(</span><span class="va">chisq_samples</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">chisq_samples</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_dots.html">stat_dots</a></span><span class="op">(</span></span>
<span>    quantiles <span class="op">=</span> <span class="fl">500</span>,</span>
<span>    layout <span class="op">=</span> <span class="st">"hex"</span>,</span>
<span>    stackratio <span class="op">=</span> <span class="fl">0.9</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>    fill <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>    na.rm <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span></span>
<span>    xintercept <span class="op">=</span> <span class="va">dtmr_dina</span><span class="op">@</span><span class="va">fit</span><span class="op">$</span><span class="va">ppmc_raw_score</span><span class="op">$</span><span class="va">obs_chisq</span>,</span>
<span>    color <span class="op">=</span> <span class="va">msr_colors</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,</span>
<span>    linewidth <span class="op">=</span> <span class="fl">1</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># scale_x_continuous(limits = c(0, 250)) +</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="cn">NULL</span>, x <span class="op">=</span> <span class="st">"&amp;chi;^2^&lt;sub&gt;rep&lt;/sub&gt;"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>, axis.ticks.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-dina-chisq-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Dot plot showing the distribution of chi-square statistics from replicated datasets. A vertical line marks the observed chi-square statistic, which falls near the center of the distribution, indicating good model fit.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-dina-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dina-chisq-dist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" alt="Dot plot showing the distribution of chi-square statistics from replicated datasets. A vertical line marks the observed chi-square statistic, which falls near the center of the distribution, indicating good model fit.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dina-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Posterior predictive χ<sup>2</sup> distribution for the DINA model.
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="relative-model-fit" class="level2"><h2 class="anchored" data-anchor-id="relative-model-fit">Relative model fit</h2>
<p>Absolute fit asks whether the model fits the data. Relative fit asks a different question: Among several candidate models, which fits better? This distinction matters because sometimes multiple models may show adequate absolute model fit, and we need to choose the best model to implement. In our example, we have one model that fits well and one that doesn’t so we don’t really need an evaluation of relative model fit to determine which is better. However, we’ll run comparison to illustrate idea.</p>
<p>We recommend using leave-one-out cross-validation (LOO) estimates for model comparisons <span class="citation" data-cites="loo-waic">(<a href="#ref-loo-waic" role="doc-biblioref">Vehtari et al., 2017</a>)</span>. LOO approximates how well the model would predict new, unseen data. Higher expected log predictive density (ELPD) values indicate better out-of-sample predictive performance. <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code> uses the <a href="https://mc-stan.org/loo/">loo</a> package to directly compare the models, rank them by ELPD and report the difference along with its standard error.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span>, <span class="va">dtmr_dina</span><span class="op">)</span></span>
<span><span class="co">#&gt;           elpd_diff se_diff</span></span>
<span><span class="co">#&gt; dtmr_lcdm    0.0       0.0 </span></span>
<span><span class="co">#&gt; dtmr_dina -195.5      19.2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The model with the higher ELPD is listed first. A difference in ELPD that is large relative to its standard error (roughly more than 2.5 times) provides strong evidence that one model genuinely fits better. Since the data was simulated from an LCDM, the LCDM should show a substantially higher ELPD than the DINA, reflecting that the LCDM is a better match for the true data-generating process.</p>
</section><section id="classification-reliability" class="level2"><h2 class="anchored" data-anchor-id="classification-reliability">Classification reliability</h2>
<p>Even after examining fit, it’s worth asking a separate question. Regardless of how well the model fits the data at an overall level, how reliable are the individual classifications it produces? For practical applications of DCMs,like providing feedback to teachers about specific competencies, the reliability of those classifications matters as much as overall model fit.</p>
<p><code><a href="https://measr.r-dcm.org/reference/reliability.html">reliability()</a></code> calculates several types of reliability evidence from our estimated model.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_reliability</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://measr.r-dcm.org/reference/reliability.html">reliability</a></span><span class="op">(</span><span class="va">dtmr_lcdm</span><span class="op">)</span></span>
<span><span class="va">lcdm_reliability</span></span>
<span><span class="co">#&gt; $pattern_reliability</span></span>
<span><span class="co">#&gt;       p_a       p_c </span></span>
<span><span class="co">#&gt; 0.7211589 0.6007968 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $map_reliability</span></span>
<span><span class="co">#&gt; $map_reliability$accuracy</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 8</span></span>
<span><span class="co">#&gt;   attribute                   acc lambda_a kappa_a youden_a tetra_a  tp_a  tn_a</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units            0.926    0.785   0.367    0.828   0.968 0.875 0.952</span></span>
<span><span class="co">#&gt; 2 partitioning_iterating    0.925    0.847   0.849    0.849   0.972 0.924 0.926</span></span>
<span><span class="co">#&gt; 3 appropriateness           0.891    0.725   0.733    0.764   0.938 0.925 0.838</span></span>
<span><span class="co">#&gt; 4 multiplicative_comparison 0.924    0.803   0.146    0.840   0.969 0.938 0.902</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $map_reliability$consistency</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 10</span></span>
<span><span class="co">#&gt;   attribute         consist lambda_c kappa_c youden_c tetra_c  tp_c  tn_c gammak</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units      0.875    0.625   0.665    0.719   0.909 0.813 0.907  0.890</span></span>
<span><span class="co">#&gt; 2 partitioning_ite…   0.868    0.733   0.849    0.736   0.915 0.870 0.866  0.889</span></span>
<span><span class="co">#&gt; 3 appropriateness     0.828    0.547   0.682    0.635   0.844 0.862 0.773  0.843</span></span>
<span><span class="co">#&gt; 4 multiplicative_c…   0.877    0.682   0.757    0.741   0.920 0.900 0.841  0.896</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: pc_prime &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $eap_reliability</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 5</span></span>
<span><span class="co">#&gt;   attribute                 rho_pf rho_bs rho_i rho_tb</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units             0.787  0.756 0.600  0.930</span></span>
<span><span class="co">#&gt; 2 partitioning_iterating     0.796  0.779 0.637  0.940</span></span>
<span><span class="co">#&gt; 3 appropriateness            0.740  0.673 0.564  0.873</span></span>
<span><span class="co">#&gt; 4 multiplicative_comparison  0.812  0.781 0.632  0.943</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>measr returns three categories of reliability: pattern reliability, MAP (maximum a posteriori) reliability, and EAP (expected a posteriori) reliability. Each reflects a different way of reporting results, and the most relevant indices depend on how proficiency scores are determined and used. For a comprehensive review of reliability methods for DCMs, see <span class="citation" data-cites="reliability-handbook">Sinharay &amp; Johnson (<a href="#ref-reliability-handbook" role="doc-biblioref">2019</a>)</span>.</p>
<section id="pattern-reliability" class="level3"><h3 class="anchored" data-anchor-id="pattern-reliability">Pattern reliability</h3>
<p>Pattern reliability evaluates the consistency and accuracy of classifying respondents into an overall profile—the complete pattern of proficiency across all attributes simultaneously. <span class="citation" data-cites="cui2012">Cui et al. (<a href="#ref-cui2012" role="doc-biblioref">2012</a>)</span> describe two indices, <code>p_a</code> and <code>p_c</code>:</p>
<ul>
<li>p<sub>a</sub> is the probability of classifying a random respondent into the correct class.</li>
<li>p<sub>c</sub> is the probability of consistently classifying a random respondent into the same class across two test administrations.</li>
</ul>
<p>These indices range from 0 to 1, with 1 indicating perfect accuracy or consistency, and 0 indicating the opposite.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_reliability</span><span class="op">$</span><span class="va">pattern_reliability</span></span>
<span><span class="co">#&gt;       p_a       p_c </span></span>
<span><span class="co">#&gt; 0.7211589 0.6007968</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="map-reliability" class="level3"><h3 class="anchored" data-anchor-id="map-reliability">MAP reliability</h3>
<p>MAP reliability evaluates accuracy and consistency at the attribute level, where each attribute is classified separately using a threshold (typically .5) applied to the estimated proficiency probability. <span class="citation" data-cites="johnson2018">Johnson &amp; Sinharay (<a href="#ref-johnson2018" role="doc-biblioref">2018</a>)</span> describe two primary indices, P<sub>ak</sub> (<code>acc</code>) and P<sub>ck</sub> (<code>consist</code>):</p>
<ul>
<li>P<sub>ak</sub> is the accuracy of the attribute classification, or how often the classification matches the true latent state.</li>
<li>P<sub>ck</sub> is the consistency of the classification across parallel test administrations.</li>
</ul>
<p>In addition, <span class="citation" data-cites="johnson2018">Johnson &amp; Sinharay (<a href="#ref-johnson2018" role="doc-biblioref">2018</a>)</span> demonstrate how other agreement indices, such as Goodman and Kruskal’s λ and Cohen’s κ, can be used to evaluate accuracy and consistency at the attribute level. All indices are returned by <code><a href="https://measr.r-dcm.org/reference/reliability.html">reliability()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_reliability</span><span class="op">$</span><span class="va">map_reliability</span></span>
<span><span class="co">#&gt; $accuracy</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 8</span></span>
<span><span class="co">#&gt;   attribute                   acc lambda_a kappa_a youden_a tetra_a  tp_a  tn_a</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units            0.926    0.785   0.367    0.828   0.968 0.875 0.952</span></span>
<span><span class="co">#&gt; 2 partitioning_iterating    0.925    0.847   0.849    0.849   0.972 0.924 0.926</span></span>
<span><span class="co">#&gt; 3 appropriateness           0.891    0.725   0.733    0.764   0.938 0.925 0.838</span></span>
<span><span class="co">#&gt; 4 multiplicative_comparison 0.924    0.803   0.146    0.840   0.969 0.938 0.902</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $consistency</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 10</span></span>
<span><span class="co">#&gt;   attribute         consist lambda_c kappa_c youden_c tetra_c  tp_c  tn_c gammak</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units      0.875    0.625   0.665    0.719   0.909 0.813 0.907  0.890</span></span>
<span><span class="co">#&gt; 2 partitioning_ite…   0.868    0.733   0.849    0.736   0.915 0.870 0.866  0.889</span></span>
<span><span class="co">#&gt; 3 appropriateness     0.828    0.547   0.682    0.635   0.844 0.862 0.773  0.843</span></span>
<span><span class="co">#&gt; 4 multiplicative_c…   0.877    0.682   0.757    0.741   0.920 0.900 0.841  0.896</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: pc_prime &lt;dbl&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="eap-reliability" class="level3"><h3 class="anchored" data-anchor-id="eap-reliability">EAP reliability</h3>
<p>EAP reliability evaluates the precision of the probability of proficiency itself, rather than a binary classification. <span class="citation" data-cites="johnson2020">Johnson &amp; Sinharay (<a href="#ref-johnson2020" role="doc-biblioref">2020</a>)</span> describe four reliability metrics for this purpose and recommend using the biserial (<code>rho_bs</code>) and informational (<code>rho_i</code>) indices, as the parallel form estimates tend to overestimate reliability.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lcdm_reliability</span><span class="op">$</span><span class="va">eap_reliability</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 5</span></span>
<span><span class="co">#&gt;   attribute                 rho_pf rho_bs rho_i rho_tb</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 referent_units             0.787  0.756 0.600  0.930</span></span>
<span><span class="co">#&gt; 2 partitioning_iterating     0.796  0.779 0.637  0.940</span></span>
<span><span class="co">#&gt; 3 appropriateness            0.740  0.673 0.564  0.873</span></span>
<span><span class="co">#&gt; 4 multiplicative_comparison  0.812  0.781 0.632  0.943</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>EAP reliability is typically lower than MAP reliability, because placing a respondent at a specific probability (a continuous scale) is harder than placing them into a binary category. That said, both MAP and EAP reliability can be adequate even when overall model fit is not perfect, which is one reason it’s important to evaluate both fit and reliability.</p>
</section></section><section id="wrapping-up" class="level2"><h2 class="anchored" data-anchor-id="wrapping-up">Wrapping up</h2>
<p>So far we’ve discussed various ways we can evaluate whether our model has good fit and provides accurate and reliable results. But what do we do if the answer is “no”? A good place to start is often examining your structural model and ensuring that attribute relationships are appropriately included. That is the focus of the <a href="../../start/hierarchies/">Define Attribute Relationships</a> article.</p>
</section><div id="quarto-appendix" class="default"><section id="session-info" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Session information</h2><div class="quarto-appendix-contents">
<div class="cell" data-layout-align="center">
<pre><code>#&gt; ─ Session info ─────────────────────────────────────────────────────
#&gt;  version      R version 4.5.2 (2025-10-31)
#&gt;  language     (EN)
#&gt;  date         2026-04-04
#&gt;  pandoc       3.9
#&gt;  quarto       1.9.24
#&gt;  Stan (rstan) 2.37.0
#&gt; 
#&gt; ─ Packages ─────────────────────────────────────────────────────────
#&gt;  package          version     date (UTC) source
#&gt;  bridgesampling   1.2-1       2025-11-19 CRAN (R 4.5.2)
#&gt;  dcmdata          0.2.0       2026-03-10 CRAN (R 4.5.2)
#&gt;  dcmstan          0.1.0       2025-11-24 CRAN (R 4.5.2)
#&gt;  dplyr            1.2.0       2026-02-03 CRAN (R 4.5.2)
#&gt;  forcats          1.0.1       2025-09-25 CRAN (R 4.5.0)
#&gt;  ggplot2          4.0.2       2026-02-03 CRAN (R 4.5.2)
#&gt;  loo              2.9.0.9000  2025-12-30 https://stan-dev.r-universe.dev (R 4.5.2)
#&gt;  lubridate        1.9.5       2026-02-04 CRAN (R 4.5.2)
#&gt;  measr            2.0.0.9000  2026-03-21 Github (r-dcm/measr@475bc50)
#&gt;  posterior        1.6.1.9000  2025-12-30 https://stan-dev.r-universe.dev (R 4.5.2)
#&gt;  purrr            1.2.1       2026-01-09 CRAN (R 4.5.2)
#&gt;  readr            2.2.0       2026-02-19 CRAN (R 4.5.2)
#&gt;  rlang            1.1.7       2026-01-09 CRAN (R 4.5.2)
#&gt;  rstan            2.36.0.9000 2025-09-26 https://stan-dev.r-universe.dev (R 4.5.1)
#&gt;  stringr          1.6.0       2025-11-04 CRAN (R 4.5.0)
#&gt;  tibble           3.3.1       2026-01-11 CRAN (R 4.5.2)
#&gt;  tidyr            1.3.2       2025-12-19 CRAN (R 4.5.2)
#&gt; 
#&gt; ────────────────────────────────────────────────────────────────────</code></pre>
</div>



</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-dtmr" class="csl-entry" role="listitem">
Bradshaw, L., Izsák, A., Templin, J., &amp; Jacobson, E. (2014). Diagnosing teachers’ understandings of rational numbers: Building a multidimensional test within the diagnostic classification framework. <em>Educational Measurement: Issues and Practice</em>, <em>33</em>(1), 2–14. <a href="https://doi.org/10.1111/emip.12020">https://doi.org/10.1111/emip.12020</a>
</div>
<div id="ref-cui2012" class="csl-entry" role="listitem">
Cui, Y., Gierl, M. J., &amp; Chang, H.-H. (2012). Estimating classification consistency and accuracy for cognitive diagnostic assessment. <em>Journal of Educational Measurement</em>, <em>49</em>(1), 19–38. <a href="https://doi.org/10.1111/j.1745-3984.2011.00158.x">https://doi.org/10.1111/j.1745-3984.2011.00158.x</a>
</div>
<div id="ref-dina" class="csl-entry" role="listitem">
<span class="nocase">de la Torre, J., &amp; Douglas, J. A.</span> (2004). Higher-order latent trait models for cognitive diagnosis. <em>Psychometrika</em>, <em>69</em>(3), 333–353. <a href="https://doi.org/10.1007/BF02295640">https://doi.org/10.1007/BF02295640</a>
</div>
<div id="ref-lcdm" class="csl-entry" role="listitem">
Henson, R. A., Templin, J. L., &amp; Willse, J. T. (2009). Defining a family of cognitive diagnosis models using log-linear models with latent variables. <em>Psychometrika</em>, <em>74</em>(2), 191–210. <a href="https://doi.org/10.1007/s11336-008-9089-5">https://doi.org/10.1007/s11336-008-9089-5</a>
</div>
<div id="ref-dtmr-strc" class="csl-entry" role="listitem">
Izsák, A., Jacobson, E., &amp; Bradshaw, L. (2019). Surveying middle-grades teachers’ reasoning about fraction arithmetic in terms of measured quantities. <em>Journal for Research in Mathematics Education</em>, <em>50</em>(2), 156–209. <a href="https://doi.org/10.5951/jresematheduc.50.2.0156">https://doi.org/10.5951/jresematheduc.50.2.0156</a>
</div>
<div id="ref-johnson2018" class="csl-entry" role="listitem">
Johnson, M. S., &amp; Sinharay, S. (2018). Measures of agreement to assess attribute-level classification accuracy and consistency for cognitive diagnostic assessments. <em>Journal of Educational Measurement</em>, <em>55</em>(4), 635–664. <a href="https://doi.org/10.1111/jedm.12196">https://doi.org/10.1111/jedm.12196</a>
</div>
<div id="ref-johnson2020" class="csl-entry" role="listitem">
Johnson, M. S., &amp; Sinharay, S. (2020). The reliability of the posterior probability of skill attainment in diagnostic classification models. <em>Journal of Educational and Behavioral Statistics</em>, <em>45</em>(1), 5–31. <a href="https://doi.org/10.3102/1076998619864550">https://doi.org/10.3102/1076998619864550</a>
</div>
<div id="ref-liu2016" class="csl-entry" role="listitem">
Liu, Y., Tian, W., &amp; Xin, T. (2016). An application of <span><span class="math inline">\(M_2\)</span></span> statistic to evaluate the fit of cognitive diagnostic models. <em>Journal of Educational and Behavioral Statistics</em>, <em>41</em>(1), 3–26. <a href="https://doi.org/10.3102/1076998615621293">https://doi.org/10.3102/1076998615621293</a>
</div>
<div id="ref-m2-2005" class="csl-entry" role="listitem">
Maydeu-Olivares, A., &amp; Joe, H. (2005). Limited- and full-information estimation and goodness-of-fit testing in <span class="math inline">\(2^n\)</span> contingency tables: <span>A</span> unified framework. <em>Journal of the American Statistical Association</em>, <em>100</em>(471), 1009–1020. <a href="https://doi.org/10.1198/016214504000002069">https://doi.org/10.1198/016214504000002069</a>
</div>
<div id="ref-m2-2006" class="csl-entry" role="listitem">
Maydeu-Olivares, A., &amp; Joe, H. (2006). Limited information goodness-of-fit testing in multidimensional contingency tables. <em>Psychometrika</em>, <em>71</em>(4), 713–732. <a href="https://doi.org/10.1007/s11336-005-1295-9">https://doi.org/10.1007/s11336-005-1295-9</a>
</div>
<div id="ref-park2015" class="csl-entry" role="listitem">
Park, J. Y., Johnson, M. S., &amp; Lee, Y.-S. (2015). Posterior predictive model checks for cognitive diagnostic models. <em>International Journal of Quantitative Research in Education</em>, <em>2</em>(3–4), 244–264. <a href="https://doi.org/10.1504/IJQRE.2015.071738">https://doi.org/10.1504/IJQRE.2015.071738</a>
</div>
<div id="ref-reliability-handbook" class="csl-entry" role="listitem">
Sinharay, S., &amp; Johnson, M. S. (2019). Measures of agreement: <span>Reliability</span>, classification accuracy, and classification consistency. In <span class="nocase">M. von Davier &amp; Y.-S. Lee (Eds.)</span>, <em>Handbook of <span>Diagnostic Classification Models</span></em> (pp. 359–377). <span>Springer International Publishing</span>. <a href="https://doi.org/10.1007/978-3-030-05584-4_17">https://doi.org/10.1007/978-3-030-05584-4_17</a>
</div>
<div id="ref-thompson-bayes" class="csl-entry" role="listitem">
Thompson, W. J. (2019). <em>Bayesian psychometrics for diagnostic assessments: <span>A</span> proof of concept</em> (Research Report Nos. No. 19-01). <span>University of Kansas; Accessible Teaching, Learning, and Assessment Systems</span>. <a href="https://doi.org/10.35542/osf.io/jzqs8">https://doi.org/10.35542/osf.io/jzqs8</a>
</div>
<div id="ref-loo-waic" class="csl-entry" role="listitem">
Vehtari, A., Gelman, A., &amp; Gabry, J. (2017). Practical <span>Bayesian</span> model evaluation using leave-one-out cross-validation and <span>WAIC</span>. <em>Statistics and Computing</em>, <em>27</em>, 1413–1432. <a href="https://doi.org/10.1007/s11222-016-9696-4">https://doi.org/10.1007/s11222-016-9696-4</a>
</div>
</div></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/r-dcm\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><span class="faux-block"><a href="../../funding.html">Supported by IES and ATLAS.</a></span> <span class="faux-block">All content licensed under<br><a href="https://creativecommons.org/licenses/by/4.0/"><i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> Creative Commons CC BY 4.0</a></span></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); return false;" role="button"> <i class="fa-solid fa-chevron-up" aria-label="chevron-up"></i> </a></p>
</div>
  </div>
</footer>


</body></html>